<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>13</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <AvaloniaResource Remove="Data\**" />
        <AvaloniaResource Include="Data\**" />
        <AvaloniaResource Remove="Assets\Localization\Resources.resx" />
        <AvaloniaResource Include="Assets\Localization\Resources.resx">
          <Generator>PublicResXFileCodeGenerator</Generator>
          <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </AvaloniaResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.5" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.5" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.5" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.5" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.5">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4-beta1" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Assets\Localization\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Views\Button\GenerateExportView.axaml.cs">
          <DependentUpon>GenerateExportView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

</Project>
