//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heart_of_Iron_Ultimate_Bravery.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heart_of_Iron_Ultimate_Bravery.Assets.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All countries.
        /// </summary>
        public static string AllCountriesText {
            get {
                return ResourceManager.GetString("AllCountriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string CheckText {
            get {
                return ResourceManager.GetString("CheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryText {
            get {
                return ResourceManager.GetString("CountryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateText {
            get {
                return ResourceManager.GetString("CreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string DivisionText {
            get {
                return ResourceManager.GetString("DivisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctrines Options.
        /// </summary>
        public static string DoctrinesOptionsText {
            get {
                return ResourceManager.GetString("DoctrinesOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctrine.
        /// </summary>
        public static string DoctrineText {
            get {
                return ResourceManager.GetString("DoctrineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportText {
            get {
                return ResourceManager.GetString("ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        public static string GamePathText {
            get {
                return ResourceManager.GetString("GamePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GenerateText {
            get {
                return ResourceManager.GetString("GenerateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string HostText {
            get {
                return ResourceManager.GetString("HostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string JoinText {
            get {
                return ResourceManager.GetString("JoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string LinearText {
            get {
                return ResourceManager.GetString("LinearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made By.
        /// </summary>
        public static string MadeByText {
            get {
                return ResourceManager.GetString("MadeByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Branches.
        /// </summary>
        public static string MaximumBranchesText {
            get {
                return ResourceManager.GetString("MaximumBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of doctrines.
        /// </summary>
        public static string MaxNbrDoctrinesText {
            get {
                return ResourceManager.GetString("MaxNbrDoctrinesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players.
        /// </summary>
        public static string MaxPlayerText {
            get {
                return ResourceManager.GetString("MaxPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod activated.
        /// </summary>
        public static string ModActivatedText {
            get {
                return ResourceManager.GetString("ModActivatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod path.
        /// </summary>
        public static string ModPathText {
            get {
                return ResourceManager.GetString("ModPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string ModText {
            get {
                return ResourceManager.GetString("ModText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        public static string MultiplayerText {
            get {
                return ResourceManager.GetString("MultiplayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of doctrines.
        /// </summary>
        public static string NbreDoctrinesText {
            get {
                return ResourceManager.GetString("NbreDoctrinesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Created.
        /// </summary>
        public static string NotCreatedText {
            get {
                return ResourceManager.GetString("NotCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsText {
            get {
                return ResourceManager.GetString("OptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plane.
        /// </summary>
        public static string PlaneText {
            get {
                return ResourceManager.GetString("PlaneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PlayersText {
            get {
                return ResourceManager.GetString("PlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string QuitText {
            get {
                return ResourceManager.GetString("QuitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate.
        /// </summary>
        public static string RegenerateText {
            get {
                return ResourceManager.GetString("RegenerateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetText {
            get {
                return ResourceManager.GetString("ResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Map.
        /// </summary>
        public static string RoadMapText {
            get {
                return ResourceManager.GetString("RoadMapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string ServerNameText {
            get {
                return ResourceManager.GetString("ServerNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string ShipText {
            get {
                return ResourceManager.GetString("ShipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneous branches.
        /// </summary>
        public static string SimultaneousBranchesText {
            get {
                return ResourceManager.GetString("SimultaneousBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string TankText {
            get {
                return ResourceManager.GetString("TankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthText {
            get {
                return ResourceManager.GetString("WidthText", resourceCulture);
            }
        }
    }
}
